name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Instalar Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1

      - name: Build
        run: |
          zig build

      - name: Test
        run: |
          zig build test

